### ISSUE TITLE
Add Tag name conventions to documentation

### ISSUE THREAD

**Issue by hms-dow** [hms-networks/flexy-cumulocity-connector#18]
Tag values can be assigned to child devices, fragments and measurement series by using the corresponding tag name conventions. they should be described in our documentation.

**Comment by hms-dow** [comment]
Support of child devices in Ewon Flexy:

The Ewon Flexy does not have a defined syntax for child devices. However, every Tag has a name and through this name could be different child devices defined. The character “/” will be used, to mark data tags that are dedicated to child devices.

Syntax definition:
- Tags that contain no “/” character
-> This data belongs directly to the gateway
-> The fragment name is the tag name
-> The series will be automatically “0”
- Tags that contain one (1) “/” character
-> This data belongs directly to the gateway
-> The fragment name is the tag name part before “/”
-> The series is the tag name part after “/”
- Tags that contain two (2) “/” characters
-> This data belongs to the child device named after the tag name part before the first “/” character
-> The fragment name is the tag name part between both “/” characters
-> The series is the tag name part after the last “/” character
- Tag name that contains more than two (2) “/” characters
-> Only the part after the third last “/” character is used as tag name with two (2) “/” characters 

Using this logic, here are a couple of examples with given Flexy tag name:

1.	One
a.	Child Device: (none)
b.	Fragment: One
c.	Series: 0
2.	One/2
a.	Child Device: (none)
b.	Fragment: One
c.	Series: 2
3.	One/Two/3
a.	Child Device: One
b.	Fragment: Two
c.	Series: 3
4.	Extra/One/Two/3
a.	Child Device: One
b.	Fragment: Two
c.	Series: 3

**Comment by alexjhawk** [comment]
Hi @hms-dow,

A documentation change to README.md is currently under review. This change will add a section for child device support, the appropriate syntax, and examples to the README.md file in the runtime section.
