### ISSUE TITLE
Grammer error in documentation 

### ISSUE THREAD

**Issue by TomKimsey** [hms-networks/flexy-cumulocity-connector#33]
![image](https://user-images.githubusercontent.com/17338468/208474358-2fa2bddd-3e47-44e1-9533-984b6c2be4a3.png)

**Comment by alexjhawk** [comment]
@TomKimsey,

Removing the 'invalid' label, as this is typically used to indicate that a PR, Issue, or other labeled entry is no longer relevant to or valid for the project.

Additionally, it looks like this error has been made within the Technical documentation.pdf document. This document is under control of the EU team, so I will reach out to them and make sure they see this.

**Comment by alexjhawk** [comment]
I reached out to the EU team, and they will update the document and send me the new version. Once I get it, I'll update the latest release, and close this issue.

**Comment by alexjhawk** [comment]
@TomKimsey,

The EU team has updated the document and it is now active for the latest release: 

https://github.com/hms-networks/flexy-cumulocity-connector/releases/tag/v1.3.2

Please let me know if you have any questions, and feel free to close this issue if you are satisfied with the outcome.
