### ISSUE TITLE
get config newlines not double escaped 

### ISSUE THREAD

**Issue by it-hms** [hms-networks/flexy-cumulocity-connector#43]
The returned string for get config does not have escaped new lines and thus causes JSON parsing exception. I'm not sure what is the reason for this.  This character should be escaped here:  https://github.com/hms-networks/flexy-cumulocity-connector/blob/4266e8e22536a14d9a27fe6ddc163d43509bf624/src/main/java/com/hms_networks/sc/cumulocity/api/CConnectorWebApiListener.java#L111

![image](https://user-images.githubusercontent.com/72526279/235459140-c57e3c6b-3b15-4129-b313-a2f627425181.png)
![image](https://user-images.githubusercontent.com/72526279/235459206-68969633-cff6-4221-b650-e374cb0e5f61.png)

**Comment by alexjhawk** [comment]
@it-hms, I've looked at this during the ongoing v1.4.1 work and have not identified the issue or replicated an exception.

I tested using my browser and two web-based JSON lint tools without encountering any issues. Additionally, the code is already implemented to escape the newlines, as they were tested to cause the mentioned issue during initial development: 
![image](https://github.com/hms-networks/flexy-cumulocity-connector/assets/51409174/671768aa-d4a3-4959-adea-0a03207dd13c)

Was there a particular JSON parsing tool or mechanism you were using?
