### ISSUE TITLE
Measurement aggregation feature

### ISSUE THREAD

**Issue by it-hms** [hms-networks/flexy-cumulocity-connector#48]
Feature would change payload format to have multiple measurements aggregated in a single payload.  This could be far more efficient use of bandwidth for some applications. This feature would also require a configurable aggregation period.  This should be a period of time where measurements in that period would be aggregated and have the same timestamp and grouped in the same payload. The would make the timestamp less accurate, but this accuracy might not be necessary. 
[Requested_Ewon_Flexy_Format.txt](https://github.com/hms-networks/flexy-cumulocity-connector/files/11637652/Requested_Ewon_Flexy_Format.txt)

**Comment by alexjhawk** [comment]
Closing as completed. Release with v1.4.0
