### ISSUE TITLE
Payload size must be limited on slow connections due to Cumulocity server disconnects. 

### ISSUE THREAD

**Issue by it-hms** [hms-networks/flexy-cumulocity-connector#50]
Over "slow" connections e.g., cellular, Cumulocity sever will consistently drop connections when a payload is over a certain size. Through testing we find this size limit to be roughly 2kB. However, this is an observation of a single device, and we have not quantified what exactly constitutes a  "slow connection". 

Furthermore, the server stops responding, but keeps the TCP keep alive. So the client depends on the MQTT keep alive to know if the connection is disconnected.  

 
![image](https://github.com/hms-networks/flexy-cumulocity-connector/assets/72526279/a3048c82-ff28-422d-98ad-bf3e7af7cfd7)

**Comment by alexjhawk** [comment]
@it-hms, Do you think this is/was related to a mismatch between MTUs? 

I'm not sure we have encountered similar issues otherwise, and it might be difficult to implement this without having a defined metric for what is considered a slow network (which could also vary greatly from device to device).

**Comment by it-hms** [comment]
> @it-hms, Do you think this is/was related to a mismatch between MTUs?
> 
> I'm not sure we have encountered similar issues otherwise, and it might be difficult to implement this without having a defined metric for what is considered a slow network (which could also vary greatly from device to device).

This is likely related to MTU size. We can close this issue.
