### ISSUE TITLE
Add support for "Transient" messages

### ISSUE THREAD

**Issue by it-hms** [hms-networks/flexy-cumulocity-connector#52]
Please add the ability to toggle measurement data transmitted to Cumulocity as "Transient" though the addition of a header text in each message: X-Cumulocity-Processing-Mode: TRANSIENT
This will allow for processing of data as it enters Cumulocity but prevent automatic storage of the measurement data

**Comment by it-hms** [comment]
I see this in the HTTP documentation as an optional header. I'm not sure about the MQTT equivalent.

**Comment by alexjhawk** [comment]
Adding detail:

MQTT equivalent involves changing the target topic(s). Typically, this just means instead of `s/`, we use `t/`, but in the case of aggregated data payloads, we simply append `t/` at the beginning since it does not use `s/` by default.
