### ISSUE TITLE
2 Reboots required to get Flexy in active connection

### ISSUE THREAD

**Issue by ChrScha** [hms-networks/flexy-cumulocity-connector#56]
For installation of the Agent there is a reboot required. 
After this the device does not send data, but requires another reboot.

One restart should be sufficient.

**Comment by alexjhawk** [comment]
Hi @ChrScha,

Thank you for reporting this.

To clarify, are you referring to the data about the Ewon device itself (such as the firmware information displayed on the device's Cumulocity page) or the historical data for tags?

Thank you,

@alexjhawk

**Comment by ChrScha** [comment]
Hi @alexjhawk,

After an initial install + reboot, data flows in; Then it stops and also my operations are not picked up by the Flexy.

![image](https://github.com/hms-networks/flexy-cumulocity-connector/assets/87694180/1f9a9bb8-fb5d-45e7-b430-a3b76560a2e2)

Something is wrong with the MQTT broker it seems.
![image](https://github.com/hms-networks/flexy-cumulocity-connector/assets/87694180/0bc20df7-af5d-4308-a8f6-f87c5d63e0f0)

I use Firmware 14.6s0 (English)
Connector 1.4.0.

**Comment by SeanThomas11** [comment]
I too have seen this issue in registering new Flexys with our dedicated tenants across multiple firmware and connector versions.  After installing the connector and initial bootstrapping configuration file and the first reboot, the JVM process begins and the Flexy downloads the CA Cert, but it hangs at the mqtt connect step requiring a reboot before registration.  After reboot the JVM continues through mqtt connect and allows for bootstrapping registration.  However it requires another reboot before accepting the device credentials, logging in and ultimately transmitting measurements.

**Comment by ChrScha** [comment]
Measurements flow in directly after the installation an registration now.

**Comment by alexjhawk** [comment]
This is great to hear. Thank you for the update, @ChrScha.
