### ISSUE TITLE
push bootstrap config down to Connector 

### ISSUE THREAD

**Issue by it-hms** [hms-networks/flexy-cumulocity-connector#7]
Potential idea for remote push of bootstrap config 
Cumulocity .jar will need to create three string tags and one Boolean: 
•	pass
•	url
•	uname
•	setComplete

The idea is that the connector can be deployed and it should monitor tags for changes. Upon change, an update action should occur. This action needs to be specified. 

The alternate path would be to have the .jar support web requests. The entire config could be posted in body, or passed via query params. This is a cleaner option

**Comment by alexjhawk** [comment]
An alternative solution has been achieved per @StefanRuhmkorf. Will close this issue.
