### ISSUE TITLE
Configurable Measurement Definition

### ISSUE THREAD

**Issue by jmoo900** [hms-networks/flexy-cumulocity-connector#71]
### Is this feature or enhancement request related to a problem?

- [X] Yes

### Feature/Enhancement Description

Would be nice if there was some configurability in terms of how measurements are sent in.  Cumulocity charges based on consumption metrics which include the number of Measurements, Alarms and Events are sent in from a device.  For instance, lets say we configure 20 tags to be sent to the Cumulocity platform.  The way that the agent currently runs, it would create 20 measurements each loop that would be sent in like:

`{
   "time": xxxxx,
   "type": "xxxxx",
   "Temperature": {
      "T": {
         "value": ##,
         "unit": "xxxx"
      }
   } 
}  `

This may be how we want to send them in especially if the values may be changing independently of other tags that we have configured to send.  But what if all 20 measurements are sent in with the same timestamp and are all being sent at the same time.  

### Feature/Enhancement Alternatives

The option to send data as a single measurement could reduce consumption by 1/20th (as well as device class reduction leading to lower cost).  I noticed you are currently using tag groups.  Seems like an opportunity to use this grouping in order to format the measurements in this way:

`{
   "time": xxxxx,
   "type": "xxxxx",
   "Tag_Group": {
      "Temperature": {
         "value": ##,
         "unit": "xxxx"
      },
      "Vibration": {
         "value": ##,
         "unit": "xxxx"
      },
      "Humidity": {
        "value": ##,
        "unit": "xxxx"
      }   
   } 
} `

In addition to the reduction in the consumption, since the values are all part of the same measurement, the streaming analytics on the Cumulocity side will only trigger a single time instead of triggering 20 times for each measurement that is sent in with the current approach.

### Code of Conduct

- [X] I agree to abide by the Code of Conduct.

**Comment by it-hms** [comment]
@jmoo900 this feature has been implemented. Please see the data aggregation feature of the connector. 
[Cumulocity Connector Data Aggregation](https://hms-networks.github.io/flexy-cumulocity-connector/#data-aggregation)

**Comment by it-hms** [comment]
For the tag groups concept do you mean the Flexy Tag groups? There are only four Flexy tag groups: A,B,C,D.

**Comment by jmoo900** [comment]
Hey @it-hms , 

That was my thought.  Use the tag groups defined on the Flexy as the measurement grouping.

Jake
