### ISSUE TITLE
[FEATURE] Clearing & Acknowledging of alarms in Cumulocity shall be propagated back to Ewon Flexy.

### ISSUE THREAD

**Issue by attkat** [hms-networks/flexy-cumulocity-connector#73]
### Is this feature or enhancement request related to a problem?

- [X] Yes

### Feature/Enhancement Description

In case an alarm was cleared / acknowledged in Cumulocity, the alarm status is unchanged in Ewon Flexy. This leads to an inconsistent status between Ewon Flexy & Cumulocity.

### Code of Conduct

- [X] I agree to abide by the Code of Conduct.

**Comment by it-hms** [comment]
I agree this feature would be a great addition. Unfortunately, I don't think this is feasible with the current Cumulocity MQTT protocols. Cumuloctiy does not provide any sort of message indicating that the alarm has be acknowledge or clear for devices. 
Here are the supported actions. 
![image](https://github.com/user-attachments/assets/c38304f7-e1b6-4d16-a233-1454fddec820)

I will close this request as my assessment is that this is not currently possible with the Cumulocity protocols. I have reached out to Cumulocity to confirm this matter.

**Comment by attkat** [comment]
Hi,

thank you for considering my suggestion. In the meantime, I have just created a Cumulocity feature idea: https://cumulocityiot.ideas.aha.io/ideas/C8YDVC-I-227

Hopefully SAG will consider and implement it in the near future.

Best regards,
Attila
