### ISSUE TITLE
jvmrun does not point to correct .jar file of the release

### ISSUE THREAD

**Issue by ksbn7** [hms-networks/flexy-cumulocity-connector#9]
jvmrun in the release 1.0.3 points to the 1.0.0 jar file hence is not started by the ewon

jvmrun from release 1.0.3 zipfile:

`-heapsize 25M -classpath /usr/flexy-cumulocity-connector-1.0.0-full.jar -emain com.hms_networks.sc.cumulocity.CConnectorMain` # # #

**Comment by alexjhawk** [comment]
Hi @ksbn7,

Thank you for the report. This bug has been resolved in the newly released version 1.1.0 of the connector.

-Alex
